package com.ajreifsnyder.IntegratedNumPad;

import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * Used to listen for and control the keypresses
 */
public class KeyController implements NativeKeyListener {

    // Mapping the codes of the integrated numpad chars to the numpad numbers
    public ArrayList<Integer> validCodes = new ArrayList<>(List.of(21, 22, 23, 35, 36, 37, 49, 50, 51, 48));
    public ArrayList<Integer> validKeys = new ArrayList<>(List.of(
            KeyEvent.VK_NUMPAD7, KeyEvent.VK_NUMPAD8, KeyEvent.VK_NUMPAD9,
            KeyEvent.VK_NUMPAD4, KeyEvent.VK_NUMPAD5, KeyEvent.VK_NUMPAD6,
            KeyEvent.VK_NUMPAD1, KeyEvent.VK_NUMPAD2, KeyEvent.VK_NUMPAD3,
            KeyEvent.VK_NUMPAD0));

    private Robot robot;

    public KeyController() {
        try {
            this.robot = new Robot();
        } catch (AWTException e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    /**
     * Replace the letter character with the numpad equivalent
     * @param keycode The code taken from the JNativeHook listener
     */
    public void press(int keycode) {
        robot.keyPress(KeyEvent.VK_BACK_SPACE);
        robot.keyRelease(KeyEvent.VK_BACK_SPACE);
        robot.keyPress(validKeys.get(validCodes.indexOf(keycode)));
        robot.keyRelease(validKeys.get(validCodes.indexOf(keycode)));
    }

    @Override
    public void nativeKeyTyped(NativeKeyEvent nativeKeyEvent) {

    }

    /**
     * Listens for valid key presses
     * @param nativeKeyEvent An event generated by JNativeHook when a key is pressed
     */
    @Override
    public void nativeKeyPressed(NativeKeyEvent nativeKeyEvent) {
        int code = nativeKeyEvent.getKeyCode();

        if (code == 1)
            System.exit(1);

        for (int c : validCodes) {
            if (c == code) {
                press(code);
            }
        }
    }

    @Override
    public void nativeKeyReleased(NativeKeyEvent nativeKeyEvent) {

    }
}
